version: '3.4'

services:

  backend:
    build: ./Yggdrasil
    container_name: p2p-backend-yggdrasil
    environment:
     - SOCKET_URL=http://localhost:3001
     - ROOM_MANAGER_URL=http://odin:3020
    restart: on-failure
    depends_on:
     - room_repository
     - heimdall
     - database
    ports:
     - "3000:3000"

  room_repository:
    build: ./Huginn
    container_name: p2p-room_repository-huginn
    environment:
     - MYSQL_HOST=database
     - MYSQL_USER=root
     - MYSQL_PASSWORD=logmigpa
     - MYSQL_DATABASE=coffeebreak
    restart: on-failure
    depends_on:
     - database
    ports:
     - "3011:3011"

  user_repository:
    build: ./Muninn
    container_name: p2p-user_repository-muninn
    environment:
     - MYSQL_HOST=database
     - MYSQL_USER=root
     - MYSQL_PASSWORD=logmigpa
     - MYSQL_DATABASE=coffeebreak
    restart: on-failure
    depends_on:
     - database
    ports:
     - "3010:3010"

  heimdall:
    build: ./Heimdall
    container_name: p2p-socket-server-heimdall
    environment:
     - MYSQL_HOST=database
     - MYSQL_USER=root
     - MYSQL_PASSWORD=logmigpa
     - MYSQL_DATABASE=coffeebreak
     - USER_REPOSITORY=http://user_repository:3010
     - ROOM_REPOSITORY=http://room_repository:3011
    restart: on-failure
    depends_on:
     - database
     - user_repository
     - room_repository
    ports:
     - "3001:3001"
  
  odin:
    build: ./Odin
    container_name: p2p-roommanager-odin
    environment:
     - ROOM_REPOSITORY_URL=http://room_repository:3011
     - SOCKET_SERVER_URL=http://localhost:3001
    restart: on-failure
    depends_on:
     - database
     - user_repository
     - room_repository
    ports:
     - "3020:3020"

  database:
    image: mysql
    container_name: p2p-database
    environment:
     - MYSQL_ROOT_PASSWORD=logmigpa
     - MYSQL_DATABASE=coffeebreak
    restart: on-failure